version: "3.8"

services:
  # Frontend Service
  frontend:
    build: ./frontend
    ports:
      - "8000:8000"
    volumes:
      - ./frontend:/app
    depends_on:
      - user_service

  # User Service (pakai SQLite)
  user_service:
    build: ./user_service
    ports:
      - "8001:8001"
    volumes:
      - ./user_service:/app

  # Vendor Database (PostgreSQL)
  vendor_db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
      POSTGRES_DB: vendor_db
    volumes:
      - vendor_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  # Vendor Service (pakai PostgreSQL)
  vendor_service:
    build: ./vendor_service
    ports:
      - "8005:8005"
    volumes:
      - ./vendor_service:/app
    depends_on:
      vendor_db:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgresql://postgres:postgres123@vendor_db:5432/vendor_db

  # Product Service (pakai SQLite)
  product_service:
    build: ./product_service
    ports:
      - "8003:8003"
    volumes:
      - ./product_service:/app
    dns:
      -8.8.8.8

  # Order Service (pakai SQLite)
  order_service:
    build: ./order_service
    ports:
      - "8004:8004"
    volumes:
      - ./order_service:/app

  # Payment Service (pakai SQLite)
  payment_service:
    build: ./payment_service
    ports:
      - "8006:8006"
    volumes:
      - ./payment_service:/app

volumes:
  vendor_data:
